name: Build & deploy lncm/ipfs on a git tag push

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    name: Build IPFS
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - arm32v6
          - arm32v7

        flavor:
          - fuse
          - nofuse

    env:
      DOCKER_BUILDKIT: 1
      APP: ipfs
      FLAV_ARCH: "${{matrix.flavor}}-${{matrix.arch}}"

    steps:
      - uses: actions/checkout@v1.0.0

      ## Set full name of a git-${TAG}
      #   fmt:  vX.Y.Z[+build<N>]
      #   NOTE: Fails if TAG is not found
      - name: Set TAG (env var)
        run: |
          TAG="$(echo "${GITHUB_REF}" | grep 'refs/tags/' | awk -F/ '{print $NF}')"
          if [[ -z "${TAG}" ]]; then
            echo "This action has to be run on a git-tag push"
            exit 1
          fi
          echo ::set-env name=TAG::"${TAG}"

      ## Set target ${ARCH}-itecture for Docker Image built in this job.  Used in `final` stage as: `FROM ${ARCH}/alpine:…`
      #   fmt:  amd64|arm32v6|arm32v8|arm64v8
      #   NOTE: Replace `arm64` with `arm64v8`
      - name: Set ARCH (env var)
        run: |
          ARCH=${{matrix.arch}}
          if [[ "${{matrix.arch}}" == "arm64" ]]; then
            ARCH="arm64v8"
          fi
          echo ::set-env name=ARCH::"${ARCH}"

      ## Set ${BUILD} number out of the pushed git-tag
      #   fmt:  build<N>
      #   NOTE: Fails if BUILD tag was not set
      - name: Set BUILD (env var)
        run: |
          BUILD="$(echo "+${TAG}" | cut -d+ -f3)"
          if [[ -z "${BUILD}" ]]; then
            echo "ERR '+build<N>' must be appended to the git tag"
            exit 1
          fi
          echo ::set-env name=BUILD::"${BUILD}"

      ## Set ${TEST_LEVEL} based on target architecture
      #   fmt:  none|simple|advanced
      #   NOTE: Fails if BUILD tag was not set
      - name: Set TEST_LEVEL (env var)
        run: |
          TEST_LEVEL=none
          if [[ "${{matrix.arch}}" == "amd64" ]]; then
            TEST_LEVEL=advanced
          fi
          echo ::set-env name=TEST_LEVEL::"${TEST_LEVEL}"

      - name: Set GOARCH & GOARM (env vars)
        if: matrix.arch != 'amd64'
        run: |
          GOARCH="$(echo "${{matrix.arch}}" | grep -oE 'arm(64)?')"
          echo ::set-env name=GOARCH::"${GOARCH}"

          GOARM="$(echo "${{matrix.arch}}" | grep arm32 | tail -c 2)"
          echo ::set-env name=GOARM::"${GOARM}"

      - name: Print ENV VARs set above
        run: |
          printf "Git tag & arch processed:\n"
          printf "    APP: %s\n"            "${APP}"
          printf "   ARCH: %s (from %s)\n"  "${ARCH}" "${{matrix.arch}}"
          printf "    TAG: %s\n"            "${TAG}"
          printf " FLAVOR: %s\n"            "${{matrix.flavor}}"
          printf "  BUILD: %s\n"            "${BUILD}"
          printf "TEST_LE: %s\n"            "${TEST_LEVEL}"
          printf " GOARCH: %s\n"            "${GOARCH}"
          printf "  GOARM: %s\n"            "${GOARM}"

      - name: Register self-compiled qemu
        if: matrix.flavor == 'fuse' && matrix.arch != 'amd64'
        env:
          QEMU_VERSION: v4.2.0
        run: docker run --rm --privileged "meedamian/simple-qemu:${QEMU_VERSION}" -p yes

      - name: Build IPFS
        run: >
          docker build --no-cache .
          --build-arg "TEST_LEVEL=${TEST_LEVEL}"
          --build-arg "ARCH=${ARCH}"
          --build-arg "GOARCH=${GOARCH}"
          --build-arg "GOARM=${GOARM}"
          --build-arg "FLAVOR=${{matrix.flavor}}"
          --label     "arch=${{matrix.arch}}"
          --label     "commit=${{github.sha}}"
          --label     "git-tag=${TAG}"
          --label     "guilty=${{github.actor}}"
          --label     "repo-url=${{github.repositoryUrl}}"
          --label     "flavor=${FLAVOR}"
          --tag       "${APP}:${FLAV_ARCH}"

      - name: Show built image details
        run: docker images "${APP}"

      - name: Save image to a .tgz file
        run: |
          mkdir -p image/
          docker save "${APP}:${FLAV_ARCH}" | gzip > "image/${APP}-${FLAV_ARCH}.tgz"

      - name: Print sha256sum of produced Docker image
        run: sha256sum "image/${APP}-${FLAV_ARCH}.tgz"

      - name: Add Docker image as build artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: docker-images
          path: image/

      - name: Extract binary from the built image
        run: |
          mkdir -p binary/
          ID=$(docker create "${APP}:${FLAV_ARCH}")
          docker cp  "${ID}:/usr/local/bin/${APP}"  binary/
          docker rm  "${ID}"
          gzip -S "-${FLAV_ARCH}.gz"  "binary/${APP}"

      - name: Print sha256sum of extracted binary
        run: sha256sum binary/*

      - name: Add raw binary as build artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: binaries
          path: binary/


  docker-hub:
    name: Tag & deploy to Docker Hub.  Only after all builds & tests succeed

    runs-on: ubuntu-18.04
    needs: build

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Setup environment
        run: |
          echo ::set-env name=DOCKER_USER::"${GITHUB_ACTOR,,}"

          SLUG="$(echo ${GITHUB_REPOSITORY,,} | sed 's/docker-//')"
          echo ::set-env name=SLUG::"${SLUG}"

          echo ::set-env name=APP::"$(echo "${SLUG}" | awk -F/ '{print $NF}')"

          TAG="$(echo "${GITHUB_REF}" | grep 'refs/tags/' | awk -F/ '{print $NF}')"
          echo ::set-env name=TAG::"${TAG}"

          echo ::set-env name=VERSION::"$(echo "${TAG}" | cut -d+ -f1)"
          echo ::set-env name=BUILD::"$(echo "+${TAG}" | cut -d+ -f3)"

      - name: Print just set ENV VARs
        run: |
          printf "Just set env vars:\n"
          printf "   USER: %s\n"  "${DOCKER_USER}"
          printf "    TAG: %s\n"  "${TAG}"
          printf "   SLUG: %s\n"  "${SLUG}"
          printf "    APP: %s\n"  "${APP}"
          printf "VERSION: %s\n"  "${VERSION}"
          printf "  BUILD: %s\n"  "${BUILD}"

      - name: Enable manifests & print Docker version
        run: |
          mkdir -p ~/.docker
          echo '{ "experimental": "enabled" }' > ~/.docker/config.json
          sudo systemctl restart docker
          docker version

      - name: Download images built in build job
        uses: actions/download-artifact@v1.0.0
        with:
          name: docker-images

      - name: Print sha256sum of downloaded images
        run: sha256sum docker-images/*

      - name: Load images locally
        run: ls -d docker-images/* | xargs -I %  docker load -i "%"

      # `ipfs:fuse-arm64`   -> `lncm/ipfs:v0.4.22-fuse-arm64-build1`
      # `ipfs:fuse-arm64`   -> `lncm/ipfs:v0.4.22-fuse-arm64`
      # `ipfs:nofuse-arm64` -> `lncm/ipfs:v0.4.22-nofuse-arm64-build1`
      # `ipfs:nofuse-arm64  -> `lncm/ipfs:v0.4.22-nofuse-arm64`
      - name: Version-tag all images
        run: |
          for tag in $(docker images ${APP} --format "{{.Tag}}"); do
            docker tag  "${APP}:${tag}"  "${SLUG}:${VERSION}-${tag}-${BUILD}"
            docker tag  "${APP}:${tag}"  "${SLUG}:${VERSION}-${tag}"
          done

      - name: List all tagged images
        run: docker images "${SLUG}"

      - name: Login to Docker Hub
        run: |
          echo "Logging in as ${DOCKER_USER}…"
          echo "${{secrets.DOCKER_TOKEN}}" | docker login -u="${DOCKER_USER}" --password-stdin

      - name: Push all images
        run: docker images "${SLUG}" --format "{{.Repository}}:{{.Tag}}" | xargs -I %  docker push %

      - name: Get convenience Docker tag suggestions
        id: tags
        uses: meeDamian/tag-suggestions@v1.0.3

      - name: Create :X.Y.Z manifests
        run: |
          ./scripts/ci-create-manifest.sh  "${SLUG}"  "${VERSION}"  "fuse"    "${VERSION}-fuse"
          ./scripts/ci-create-manifest.sh  "${SLUG}"  "${VERSION}"  "nofuse"  "${VERSION}-nofuse"
          ./scripts/ci-create-manifest.sh  "${SLUG}"  "${VERSION}"  "nofuse"

      - name: Create :X.Y manifests
        if: steps.tags.outputs.minor != ''
        run: |
          SHORT="${{steps.tags.outputs.minor}}"
          ./scripts/ci-create-manifest.sh  "${SLUG}"  "${VERSION}"  "fuse"    "${SHORT}-fuse"
          ./scripts/ci-create-manifest.sh  "${SLUG}"  "${VERSION}"  "nofuse"  "${SHORT}-nofuse"
          ./scripts/ci-create-manifest.sh  "${SLUG}"  "${VERSION}"  "nofuse"

      - name: Create :X manifests
        if: steps.tags.outputs.major != ''
        run: |
          SHORT="${{steps.tags.outputs.major}}"
          ./scripts/ci-create-manifest.sh  "${SLUG}"  "${VERSION}"  "fuse"    "${SHORT}-fuse"
          ./scripts/ci-create-manifest.sh  "${SLUG}"  "${VERSION}"  "nofuse"  "${SHORT}-nofuse"
          ./scripts/ci-create-manifest.sh  "${SLUG}"  "${VERSION}"  "nofuse"

      - name: Create :latest manifests
        if: steps.tags.outputs.latest != ''
        run: |
          ./scripts/ci-create-manifest.sh  "${SLUG}"  "${VERSION}"  "fuse"    "fuse"
          ./scripts/ci-create-manifest.sh  "${SLUG}"  "${VERSION}"  "nofuse"  "nofuse"
          ./scripts/ci-create-manifest.sh  "${SLUG}"  "${VERSION}"  "nofuse"  "${{steps.tags.outputs.latest}}"

      - name: List all tagged images
        run: docker images "${SLUG}"


  github-release:
    name: Create Github Release. Only after successful build of a pushed git tag
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Download binaries from build artifacts
        uses: actions/download-artifact@v1.0.0
        with:
          name: binaries

      - name: Print checksums of binaries
        run: sha256sum binaries/*

      - name: Upload binaries to Github Release
        uses: meeDamian/github-release@v1.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          gzip: false
          files: binaries/*
