name: Build & test on any push

on:
  - push
  - pull_request

jobs:
  build:
    name: Build IPFS
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
          - arm32v6
          - arm32v7

        flavor:
          - fuse
          - nofuse

    env:
      DOCKER_BUILDKIT: 1
      APP: ipfs
      FLAV_ARCH: "${{matrix.flavor}}-${{matrix.arch}}"

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Setup environment
        if: matrix.arch != 'amd64'
        run: |
          ARCH="${{matrix.arch}}"
          if [[ "${{matrix.arch}}" == "arm64" ]]; then
            ARCH="arm64v8"
          fi
          echo ::set-env name=ARCH::"${ARCH}"

          GOARCH="$(echo "${{matrix.arch}}" | grep -oE 'arm(64)?')"
          echo ::set-env name=GOARCH::"${GOARCH}"

          GOARM="$(echo "${{matrix.arch}}" | grep arm32 | tail -c 2)"
          echo ::set-env name=GOARM::"${GOARM}"

      - name: Build & test IPFS (same CPU)
        if: matrix.arch == 'amd64'
        run: >
          docker build --no-cache .
          --build-arg "TEST_LEVEL=advanced"
          --build-arg "FLAVOR=${{matrix.flavor}}"
          --tag       "${APP}:${FLAV_ARCH}"

      # NOTE: `--target="final-*"` used here due to usage of `ONBUILD` tags
      - name: Build IPFS (cross-compile)
        if: matrix.arch != 'amd64'
        run: >
          docker build --no-cache .
          --build-arg "TEST_LEVEL=none"
          --build-arg "ARCH=${ARCH}"
          --build-arg "GOARCH=${GOARCH}"
          --build-arg "GOARM=${GOARM}"
          --target    "final-${{matrix.flavor}}"
          --tag       "${APP}:${FLAV_ARCH}"

      - name: Show built image details
        run: docker images ipfs

      - name: Save image to a .tgz file
        run: |
          mkdir -p image/
          docker save "${APP}:${FLAV_ARCH}" | gzip > "image/${APP}-${FLAV_ARCH}.tgz"

      - name: Print sha256sum of produced Docker image
        run: sha256sum "image/${APP}-${FLAV_ARCH}.tgz"

      - name: Add Docker image as build artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: docker-images
          path: image/

      - name: Extract binary from the built image
        run: |
          mkdir -p binary/
          ID=$(docker create "${APP}:${FLAV_ARCH}")
          docker cp  "${ID}:/usr/local/bin/ipfs"  binary/
          docker rm  "${ID}"

          gzip -S "-${FLAV_ARCH}.gz" binary/ipfs

      - name: Print sha256sum of extracted binary
        run: sha256sum binary/*

      - name: Add raw binary as build artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: binaries
          path: binary/
